---
# the number of teams playing in this event
num_teams: 5

# postgres settings
sinks:
  postgres:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    database: quincy
    ssl_mode: prefer

# credential lists used by one or more service
user_lists:
  - name: local users
    users:
      - username: geraldo # usernames and passwords
        password: BuyMyNFT1!
      - username: adora
        password: GetV4p0rized!

  - name: simple domain
    # you can specify one, both, or neither of the domain options
    # just depends on what you need for your checks
    domain: quin.cy
    netbios: QUIN
    users:
      - username: geraldo
        password: BuyMyNFT1!
      - username: adora
        password: GetV4p0rized!

  - name: complex domain
    # these can be templates if you want
    # this is handled by your check logic, the api dgaf
    domain: team{}.quin.cy
    netbios: QUIN{}
    users:
      - username: geraldo
        password: BuyMyNFT1!
      - username: adora
        password: GetV4p0rized!

# list of servers
boxes:
  - name: cubism
    host: 127.0.0.1 # can be a static ip
    services:
      - name: fileshare
        check: 75percent.py
        user_list: local users

      - name: remoting
        check: 25percent.py
        user_list: complex domain

  - name: scrapyard
    host: 127.0.0.{} # ip or dns name template
    services:
      - name: blog
        check: 100percent.py # what script does the agent run?

      - name: shop
        check: 50percent.py
        timeout: 0.5 # custom timeouts (in seconds) can be provided

      - name: ssh-ad
        check: 0percent.py
        user_list: complex domain # optional userlist name
        timeout: 30 # can be very long or very short

# http server settings
http:
  host: 127.0.0.1
  port: 8888
