name: build and release

# run on pushes to main and when manually triggered
on:
  push:
    branches: [main]
  workflow_dispatch:

# write permissions needed to create tag and release
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # checkout repo
      - uses: actions/checkout@v4
        with:
          # clone the entire repo, not just the most recent commit
          # needed for auto versioning
          fetch-depth: 0 

      # install golang dependencies
      - uses: actions/setup-go@v5
        with:
          go-version-file: src/go.mod

      # create the version tag from recent branch
      - name: generate tag
        id: tag
        run: |
          echo "tag=v0.0.$(git rev-list --count HEAD)-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      # build agent and api for:
      #   linux-amd64
      #   linux-arm64    (disabled)
      #   darwin-amd64   (disabled)
      #   darwin-arm64   (disabled)
      #   windows-amd64  (disabled)
      # LDFLAGS sets the version number in the binary at build time
      - name: build binaries
        run: |
          LDFLAGS="-X github.com/HackUCF/Quincy/cmd.Version=${{ steps.tag.outputs.tag }}"
          GOOS=linux   GOARCH=amd64 go build -C src -ldflags "$LDFLAGS" -o ../dist/quincy-linux-amd64 .
          # GOOS=linux   GOARCH=arm64 go build -C src -ldflags "$LDFLAGS" -o ../dist/quincy-linux-arm64 .
          # GOOS=darwin  GOARCH=amd64 go build -C src -ldflags "$LDFLAGS" -o ../dist/quincy-darwin-amd64 .
          # GOOS=darwin  GOARCH=arm64 go build -C src -ldflags "$LDFLAGS" -o ../dist/quincy-darwin-arm64 .
          # GOOS=windows GOARCH=amd64 go build -C src -ldflags "$LDFLAGS" -o ../dist/quincy-windows-amd64.exe .

      # release the binaries under the tag
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          generate_release_notes: true
          files: dist/*